// Code generated by yasupGen; DO NOT EDIT.

package yasup

import (
	crypto "crypto/rand"
	"math/big"
	"math/rand"
)

//BoolInsert will append elem at the position i. Might return ErrIndexOutOfBounds.
func BoolInsert(sl *[]bool, elem bool, i int) error {
	if i < 0 || i > len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append(*sl, elem)
	copy((*sl)[i+1:], (*sl)[i:])
	(*sl)[i] = elem
	return nil
}

//BoolDelete delete the element at the position i. Might return ErrIndexOutOfBounds.
func BoolDelete(sl *[]bool, i int) error {
	if i < 0 || i >= len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append((*sl)[:i], (*sl)[i+1:]...)
	return nil
}

//BoolPush is equivalent to BoolInsert with index len(*sl)
func BoolPush(sl *[]bool, elem bool) {
	BoolInsert(sl, elem, len(*sl))
}

//BoolPop is equivalent to getting and removing the last element of the slice. Might return ErrEmptySlice.
func BoolPop(sl *[]bool) (bool, error) {
	if len(*sl) == 0 {
		var zeroVal bool
		return zeroVal, ErrEmptySlice
	}
	last := len(*sl) - 1
	ret := (*sl)[last]
	BoolDelete(sl, last)
	return ret, nil
}

//BoolEquals compares two bool slices. Returns true if their elements are equal.
func BoolEquals(a, b []bool) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

//BoolFastShuffle will randomly swap the bool elements of a slice using math/rand (fast but not cryptographycally secure).
func BoolFastShuffle(sp []bool) {
	rand.Shuffle(len(sp), func(i, j int) {
		sp[i], sp[j] = sp[j], sp[i]
	})
}

//BoolSecureShuffle will randomly swap the bool elements of a slice using crypto/rand (resource intensive but cryptographycally secure).
func BoolSecureShuffle(sp []bool) error {
	var i int64
	size := int64(len(sp)) - 1
	for i = 0; i < size+1; i++ {
		bigRandI, err := crypto.Int(crypto.Reader, big.NewInt(size))
		if err != nil {
			return err
		}
		randI := bigRandI.Int64()
		sp[size-i], sp[randI] = sp[randI], sp[size-i]
	}
	return nil
}
