// Code generated by yasupGen; DO NOT EDIT.

package yasup

import (
	crypto "crypto/rand"
	"math/big"
	"math/rand"
)

var zeroValueBool bool

//BoolInsert will append elem at the position i. Might return ErrIndexOutOfBounds.
func BoolInsert(sl *[]bool, elem bool, i int) error {
	if i < 0 || i > len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append(*sl, elem)
	copy((*sl)[i+1:], (*sl)[i:])
	(*sl)[i] = elem
	return nil
}

//BoolDelete delete the element at the position i. Might return ErrIndexOutOfBounds.
func BoolDelete(sl *[]bool, i int) error {
	if i < 0 || i >= len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append((*sl)[:i], (*sl)[i+1:]...)
	return nil
}

//BoolContains will return true if elem is present in the slice and false otherwise.
func BoolContains(sl []bool, elem bool) bool {
	for i := range sl {
		if sl[i] == elem {
			return true
		}
	}
	return false
}

//BoolIndex returns the index of the first instance of elem, or -1 if elem is not present.
func BoolIndex(sl []bool, elem bool) int {
	for i := range sl {
		if sl[i] == elem {
			return i
		}
	}
	return -1
}

//BoolLastIndex returns the index of the last instance of elem in the slice, or -1 if elem is not present.
func BoolLastIndex(sl []bool, elem bool) int {
	for i := len(sl) - 1; i >= 0; i-- {
		if sl[i] == elem {
			return i
		}
	}
	return -1
}

//BoolCount will return an int representing the amount of times that elem is present in the slice.
func BoolCount(sl []bool, elem bool) int {
	var n int
	for i := range sl {
		if sl[i] == elem {
			n++
		}
	}
	return n
}

//BoolPush is equivalent to BoolInsert with index len(*sl).
func BoolPush(sl *[]bool, elem bool) {
	BoolInsert(sl, elem, len(*sl))
}

//BoolFrontPush is equivalent to BoolInsert with index 0.
func BoolFrontPush(sl *[]bool, elem bool) {
	BoolInsert(sl, elem, 0)
}

//BoolPop is equivalent to getting and removing the last element of the slice. Might return ErrEmptySlice.
func BoolPop(sl *[]bool) (bool, error) {
	if len(*sl) == 0 {
		return zeroValueBool, ErrEmptySlice
	}
	last := len(*sl) - 1
	ret := (*sl)[last]
	BoolDelete(sl, last)
	return ret, nil
}

//BoolPop is equivalent to getting and removing the first element of the slice. Might return ErrEmptySlice.
func BoolFrontPop(sl *[]bool) (bool, error) {
	if len(*sl) == 0 {
		return zeroValueBool, ErrEmptySlice
	}
	ret := (*sl)[0]
	BoolDelete(sl, 0)
	return ret, nil
}

//BoolReplace modifies the slice with the first n non-overlapping instances of old replaced by new. If n equals -1, there is no limit on the number of replacements.
func BoolReplace(sl []bool, old, new bool, n int) (replacements int) {
	left := n
	for i := range sl {
		if left == 0 {
			break // no replacements left
		}
		if sl[i] == old {
			sl[i] = new
			left--
		}
	}
	return n - left
}

//BoolReplaceAll is equivalent to BoolReplace with n = -1.
func BoolReplaceAll(sl []bool, old, new bool) (replacements int) {
	return BoolReplace(sl, old, new, -1)
}

//BoolEquals compares two bool slices. Returns true if their elements are equal.
func BoolEquals(a, b []bool) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

//BoolFastShuffle will randomly swap the bool elements of a slice using math/rand (fast but not cryptographycally secure).
func BoolFastShuffle(sp []bool) {
	rand.Shuffle(len(sp), func(i, j int) {
		sp[i], sp[j] = sp[j], sp[i]
	})
}

//BoolSecureShuffle will randomly swap the bool elements of a slice using crypto/rand (resource intensive but cryptographically secure).
func BoolSecureShuffle(sp []bool) error {
	var i int64
	size := int64(len(sp)) - 1
	for i = 0; i < size+1; i++ {
		bigRandI, err := crypto.Int(crypto.Reader, big.NewInt(size))
		if err != nil {
			return err
		}
		randI := bigRandI.Int64()
		sp[size-i], sp[randI] = sp[randI], sp[size-i]
	}
	return nil
}
