// Code generated by yasupGen; DO NOT EDIT.

package yasup

import (
	crypto "crypto/rand"
	"math/big"
	"math/rand"
)

var zeroValueByte byte

//ByteInsert will append elem at the position i. Might return ErrIndexOutOfBounds.
func ByteInsert(sl *[]byte, elem byte, i int) error {
	if i < 0 || i > len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append(*sl, elem)
	copy((*sl)[i+1:], (*sl)[i:])
	(*sl)[i] = elem
	return nil
}

//ByteDelete delete the element at the position i. Might return ErrIndexOutOfBounds.
func ByteDelete(sl *[]byte, i int) error {
	if i < 0 || i >= len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append((*sl)[:i], (*sl)[i+1:]...)
	return nil
}

//ByteContains will return true if elem is present in the slice and false otherwise.
func ByteContains(sl []byte, elem byte) bool {
	for i := range sl {
		if sl[i] == elem {
			return true
		}
	}
	return false
}

//ByteIndex returns the index of the first instance of elem, or -1 if elem is not present.
func ByteIndex(sl []byte, elem byte) int {
	for i := range sl {
		if sl[i] == elem {
			return i
		}
	}
	return -1
}

//ByteLastIndex returns the index of the last instance of elem in the slice, or -1 if elem is not present.
func ByteLastIndex(sl []byte, elem byte) int {
	for i := len(sl) - 1; i >= 0; i-- {
		if sl[i] == elem {
			return i
		}
	}
	return -1
}

//ByteCount will return an int representing the amount of times that elem is present in the slice.
func ByteCount(sl []byte, elem byte) int {
	var n int
	for i := range sl {
		if sl[i] == elem {
			n++
		}
	}
	return n
}

//BytePush is equivalent to ByteInsert with index len(*sl).
func BytePush(sl *[]byte, elem byte) {
	ByteInsert(sl, elem, len(*sl))
}

//ByteFrontPush is equivalent to ByteInsert with index 0.
func ByteFrontPush(sl *[]byte, elem byte) {
	ByteInsert(sl, elem, 0)
}

//BytePop is equivalent to getting and removing the last element of the slice. Might return ErrEmptySlice.
func BytePop(sl *[]byte) (byte, error) {
	if len(*sl) == 0 {
		return zeroValueByte, ErrEmptySlice
	}
	last := len(*sl) - 1
	ret := (*sl)[last]
	ByteDelete(sl, last)
	return ret, nil
}

//BytePop is equivalent to getting and removing the first element of the slice. Might return ErrEmptySlice.
func ByteFrontPop(sl *[]byte) (byte, error) {
	if len(*sl) == 0 {
		return zeroValueByte, ErrEmptySlice
	}
	ret := (*sl)[0]
	ByteDelete(sl, 0)
	return ret, nil
}

//ByteReplace modifies the slice with the first n non-overlapping instances of old replaced by new. If n equals -1, there is no limit on the number of replacements.
func ByteReplace(sl []byte, old, new byte, n int) (replacements int) {
	left := n
	for i := range sl {
		if left == 0 {
			break // no replacements left
		}
		if sl[i] == old {
			sl[i] = new
			left--
		}
	}
	return n - left
}

//ByteReplaceAll is equivalent to ByteReplace with n = -1.
func ByteReplaceAll(sl []byte, old, new byte) (replacements int) {
	return ByteReplace(sl, old, new, -1)
}

//ByteEquals compares two byte slices. Returns true if their elements are equal.
func ByteEquals(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

//ByteFastShuffle will randomly swap the byte elements of a slice using math/rand (fast but not cryptographycally secure).
func ByteFastShuffle(sp []byte) {
	rand.Shuffle(len(sp), func(i, j int) {
		sp[i], sp[j] = sp[j], sp[i]
	})
}

//ByteSecureShuffle will randomly swap the byte elements of a slice using crypto/rand (resource intensive but cryptographically secure).
func ByteSecureShuffle(sp []byte) error {
	var i int64
	size := int64(len(sp)) - 1
	for i = 0; i < size+1; i++ {
		bigRandI, err := crypto.Int(crypto.Reader, big.NewInt(size))
		if err != nil {
			return err
		}
		randI := bigRandI.Int64()
		sp[size-i], sp[randI] = sp[randI], sp[size-i]
	}
	return nil
}
