// Code generated by yasupGen; DO NOT EDIT.

package yasup

import (
	crypto "crypto/rand"
	"math/big"
	"math/rand"
)

var zeroValueComplex128 complex128

//Complex128Contains will return true if elem is present in the slice and false otherwise.
func Complex128Contains(sl []complex128, elem complex128) bool {
	for i := range sl {
		if sl[i] == elem {
			return true
		}
	}
	return false
}

//Complex128Insert will append elem at the position i. Might return ErrIndexOutOfBounds.
func Complex128Insert(sl *[]complex128, elem complex128, i int) error {
	if i < 0 || i > len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append(*sl, elem)
	copy((*sl)[i+1:], (*sl)[i:])
	(*sl)[i] = elem
	return nil
}

//Complex128Delete delete the element at the position i. Might return ErrIndexOutOfBounds.
func Complex128Delete(sl *[]complex128, i int) error {
	if i < 0 || i >= len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append((*sl)[:i], (*sl)[i+1:]...)
	return nil
}

//Complex128Push is equivalent to Complex128Insert with index len(*sl)
func Complex128Push(sl *[]complex128, elem complex128) {
	Complex128Insert(sl, elem, len(*sl))
}

//Complex128FrontPush is equivalent to Complex128Insert with index 0
func Complex128FrontPush(sl *[]complex128, elem complex128) {
	Complex128Insert(sl, elem, 0)
}

//Complex128Pop is equivalent to getting and removing the last element of the slice. Might return ErrEmptySlice.
func Complex128Pop(sl *[]complex128) (complex128, error) {
	if len(*sl) == 0 {
		return zeroValueComplex128, ErrEmptySlice
	}
	last := len(*sl) - 1
	ret := (*sl)[last]
	Complex128Delete(sl, last)
	return ret, nil
}

//Complex128Pop is equivalent to getting and removing the first element of the slice. Might return ErrEmptySlice.
func Complex128FrontPop(sl *[]complex128) (complex128, error) {
	if len(*sl) == 0 {
		return zeroValueComplex128, ErrEmptySlice
	}
	ret := (*sl)[0]
	Complex128Delete(sl, 0)
	return ret, nil
}

//Complex128Equals compares two complex128 slices. Returns true if their elements are equal.
func Complex128Equals(a, b []complex128) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

//Complex128FastShuffle will randomly swap the complex128 elements of a slice using math/rand (fast but not cryptographycally secure).
func Complex128FastShuffle(sp []complex128) {
	rand.Shuffle(len(sp), func(i, j int) {
		sp[i], sp[j] = sp[j], sp[i]
	})
}

//Complex128SecureShuffle will randomly swap the complex128 elements of a slice using crypto/rand (resource intensive but cryptographycally secure).
func Complex128SecureShuffle(sp []complex128) error {
	var i int64
	size := int64(len(sp)) - 1
	for i = 0; i < size+1; i++ {
		bigRandI, err := crypto.Int(crypto.Reader, big.NewInt(size))
		if err != nil {
			return err
		}
		randI := bigRandI.Int64()
		sp[size-i], sp[randI] = sp[randI], sp[size-i]
	}
	return nil
}
