// Code generated by yasupGen; DO NOT EDIT.

package yasup

var (
	ErrIndexOutOfBounds = yasupError{"Index out of bounds"}
	ErrEmptySlice       = yasupError{"The slice is empty but the operation requires at least one element on it"}
)

type yasupError struct {
	msg string
}

func (e yasupError) Error() string {
	return e.msg
}
