// Code generated by yasupGen; DO NOT EDIT.

package yasup_test

import (
	yasup "github.com/j4rv/yasup"
	"testing"
)

func Test_Float32Insert(t *testing.T) {
	type testCase struct {
		name     string
		slice    []float32
		insertAt int
	}
	base := []float32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
	tcs := []testCase{
		{"First", []float32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 0},
		{"Middle", []float32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, len(base) / 2},
		{"Last", []float32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, len(base)},
		{"Empty slice", []float32{}, 0},
		{"Nil slice", nil, 0},
	}
	for _, tc := range tcs {
		yasup.Float32Insert(&tc.slice, -2147483648, tc.insertAt)
		if tc.slice[tc.insertAt] != -2147483648 {
			t.Error(tc)
		}
	}
}

func Test_Float32FastShuffle(t *testing.T) {
	shuffles := [][]float32{}
	for i := 0; i < 8; i++ {
		or := []float32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
		yasup.Float32FastShuffle(or)
		shuffles = append(shuffles, or)
	}
	for i := range shuffles {
		for j := range shuffles {
			if i >= j {
				continue
			}
			if yasup.Float32Equals(shuffles[i], shuffles[j]) {
				// If there is any collision in 8 shuffles, the Shuffle function is probably broken
				t.Fail()
			}
		}
	}
	// check that nil does not panic
	yasup.Float32FastShuffle(nil)
}

func Test_Float32SecureShuffle(t *testing.T) {
	shuffles := [][]float32{}
	for i := 0; i < 8; i++ {
		or := []float32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
		yasup.Float32SecureShuffle(or)
		shuffles = append(shuffles, or)
	}
	for i := range shuffles {
		for j := range shuffles {
			if i >= j {
				continue
			}
			if yasup.Float32Equals(shuffles[i], shuffles[j]) {
				// If there is any collision in 8 shuffles, the Shuffle function is probably broken
				t.Fail()
			}
		}
	}
	// check that nil does not panic
	yasup.Float32SecureShuffle(nil)
}

func Test_Float32Equals(t *testing.T) {
	type TestCase struct {
		name string
		a, b []float32
		exp  bool
	}
	tcs := []TestCase{
		// nil checks
		{"Equals nil", nil, nil, true},
		// golang treats empty and nil slices as the same thing in most cases, we'll do the same
		{"Left nil, right empty", nil, []float32{}, true},
		{"Right nil, left empty", []float32{}, nil, true},
		{"Left nil, right not empty", nil, []float32{-2147483648}, false},
		{"Right nil, left not empty", []float32{-2147483648}, nil, false},

		{"Equals empty", []float32{}, []float32{}, true},
		{"Equals 1", []float32{-2147483648}, []float32{-2147483648}, true},
		{"Equals 2", []float32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, []float32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, true},
		{"Not equals 1", []float32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, []float32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, -2147483648}, false},
		{"Not equals 2", []float32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, []float32{}, false},
		{"Not equals 3", []float32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, []float32{-2147483648, -2147483648}, false},
	}
	for _, tc := range tcs {
		got := yasup.Float32Equals(tc.a, tc.b)
		if got != tc.exp {
			t.Error(tc)
		}
	}
}
