// Code generated by yasupGen; DO NOT EDIT.

package yasup

import (
	crypto "crypto/rand"
	"math/big"
	"math/rand"
)

var zeroValueInt16 int16

//Int16Insert will append elem at the position i. Might return ErrIndexOutOfBounds.
func Int16Insert(sl *[]int16, elem int16, i int) error {
	if i < 0 || i > len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append(*sl, elem)
	copy((*sl)[i+1:], (*sl)[i:])
	(*sl)[i] = elem
	return nil
}

//Int16Delete delete the element at the position i. Might return ErrIndexOutOfBounds.
func Int16Delete(sl *[]int16, i int) error {
	if i < 0 || i >= len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append((*sl)[:i], (*sl)[i+1:]...)
	return nil
}

//Int16Contains will return true if elem is present in the slice and false otherwise.
func Int16Contains(sl []int16, elem int16) bool {
	for i := range sl {
		if sl[i] == elem {
			return true
		}
	}
	return false
}

//Int16Index returns the index of the first instance of elem, or -1 if elem is not present.
func Int16Index(sl []int16, elem int16) int {
	for i := range sl {
		if sl[i] == elem {
			return i
		}
	}
	return -1
}

//Int16Push is equivalent to Int16Insert with index len(*sl).
func Int16Push(sl *[]int16, elem int16) {
	Int16Insert(sl, elem, len(*sl))
}

//Int16FrontPush is equivalent to Int16Insert with index 0.
func Int16FrontPush(sl *[]int16, elem int16) {
	Int16Insert(sl, elem, 0)
}

//Int16Pop is equivalent to getting and removing the last element of the slice. Might return ErrEmptySlice.
func Int16Pop(sl *[]int16) (int16, error) {
	if len(*sl) == 0 {
		return zeroValueInt16, ErrEmptySlice
	}
	last := len(*sl) - 1
	ret := (*sl)[last]
	Int16Delete(sl, last)
	return ret, nil
}

//Int16Pop is equivalent to getting and removing the first element of the slice. Might return ErrEmptySlice.
func Int16FrontPop(sl *[]int16) (int16, error) {
	if len(*sl) == 0 {
		return zeroValueInt16, ErrEmptySlice
	}
	ret := (*sl)[0]
	Int16Delete(sl, 0)
	return ret, nil
}

//Int16Equals compares two int16 slices. Returns true if their elements are equal.
func Int16Equals(a, b []int16) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

//Int16FastShuffle will randomly swap the int16 elements of a slice using math/rand (fast but not cryptographycally secure).
func Int16FastShuffle(sp []int16) {
	rand.Shuffle(len(sp), func(i, j int) {
		sp[i], sp[j] = sp[j], sp[i]
	})
}

//Int16SecureShuffle will randomly swap the int16 elements of a slice using crypto/rand (resource intensive but cryptographically secure).
func Int16SecureShuffle(sp []int16) error {
	var i int64
	size := int64(len(sp)) - 1
	for i = 0; i < size+1; i++ {
		bigRandI, err := crypto.Int(crypto.Reader, big.NewInt(size))
		if err != nil {
			return err
		}
		randI := bigRandI.Int64()
		sp[size-i], sp[randI] = sp[randI], sp[size-i]
	}
	return nil
}
