// Code generated by yasupGen; DO NOT EDIT.

package yasup

import (
	crypto "crypto/rand"
	"math/big"
	"math/rand"
)

var zeroValueInt64 int64

//Int64Insert will append elem at the position i. Might return ErrIndexOutOfBounds.
func Int64Insert(sl *[]int64, elem int64, i int) error {
	if i < 0 || i > len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append(*sl, elem)
	copy((*sl)[i+1:], (*sl)[i:])
	(*sl)[i] = elem
	return nil
}

//Int64Delete delete the element at the position i. Might return ErrIndexOutOfBounds.
func Int64Delete(sl *[]int64, i int) error {
	if i < 0 || i >= len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append((*sl)[:i], (*sl)[i+1:]...)
	return nil
}

//Int64Contains will return true if elem is present in the slice and false otherwise.
func Int64Contains(sl []int64, elem int64) bool {
	for i := range sl {
		if sl[i] == elem {
			return true
		}
	}
	return false
}

//Int64Index returns the index of the first instance of elem, or -1 if elem is not present.
func Int64Index(sl []int64, elem int64) int {
	for i := range sl {
		if sl[i] == elem {
			return i
		}
	}
	return -1
}

//Int64LastIndex returns the index of the last instance of elem in the slice, or -1 if elem is not present.
func Int64LastIndex(sl []int64, elem int64) int {
	for i := len(sl) - 1; i >= 0; i-- {
		if sl[i] == elem {
			return i
		}
	}
	return -1
}

//Int64Count will return an int representing the amount of times that elem is present in the slice.
func Int64Count(sl []int64, elem int64) int {
	var n int
	for i := range sl {
		if sl[i] == elem {
			n++
		}
	}
	return n
}

//Int64Push is equivalent to Int64Insert with index len(*sl).
func Int64Push(sl *[]int64, elem int64) {
	Int64Insert(sl, elem, len(*sl))
}

//Int64FrontPush is equivalent to Int64Insert with index 0.
func Int64FrontPush(sl *[]int64, elem int64) {
	Int64Insert(sl, elem, 0)
}

//Int64Pop is equivalent to getting and removing the last element of the slice. Might return ErrEmptySlice.
func Int64Pop(sl *[]int64) (int64, error) {
	if len(*sl) == 0 {
		return zeroValueInt64, ErrEmptySlice
	}
	last := len(*sl) - 1
	ret := (*sl)[last]
	Int64Delete(sl, last)
	return ret, nil
}

//Int64Pop is equivalent to getting and removing the first element of the slice. Might return ErrEmptySlice.
func Int64FrontPop(sl *[]int64) (int64, error) {
	if len(*sl) == 0 {
		return zeroValueInt64, ErrEmptySlice
	}
	ret := (*sl)[0]
	Int64Delete(sl, 0)
	return ret, nil
}

//Int64Replace modifies the slice with the first n non-overlapping instances of old replaced by new. If n equals -1, there is no limit on the number of replacements.
func Int64Replace(sl []int64, old, new int64, n int) (replacements int) {
	left := n
	for i := range sl {
		if left == 0 {
			break // no replacements left
		}
		if sl[i] == old {
			sl[i] = new
			left--
		}
	}
	return n - left
}

//Int64ReplaceAll is equivalent to Int64Replace with n = -1.
func Int64ReplaceAll(sl []int64, old, new int64) (replacements int) {
	return Int64Replace(sl, old, new, -1)
}

//Int64Equals compares two int64 slices. Returns true if their elements are equal.
func Int64Equals(a, b []int64) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

//Int64FastShuffle will randomly swap the int64 elements of a slice using math/rand (fast but not cryptographycally secure).
func Int64FastShuffle(sp []int64) {
	rand.Shuffle(len(sp), func(i, j int) {
		sp[i], sp[j] = sp[j], sp[i]
	})
}

//Int64SecureShuffle will randomly swap the int64 elements of a slice using crypto/rand (resource intensive but cryptographically secure).
func Int64SecureShuffle(sp []int64) error {
	var i int64
	size := int64(len(sp)) - 1
	for i = 0; i < size+1; i++ {
		bigRandI, err := crypto.Int(crypto.Reader, big.NewInt(size))
		if err != nil {
			return err
		}
		randI := bigRandI.Int64()
		sp[size-i], sp[randI] = sp[randI], sp[size-i]
	}
	return nil
}
