// Code generated by yasupGen; DO NOT EDIT.

package yasup

import (
	crypto "crypto/rand"
	"math/big"
	"math/rand"
)

//Int64Insert will append elem at the position i. Might return ErrIndexOutOfBounds.
func Int64Insert(sl *[]int64, elem int64, i int) error {
	if i < 0 || i > len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append(*sl, elem)
	copy((*sl)[i+1:], (*sl)[i:])
	(*sl)[i] = elem
	return nil
}

//Int64Delete delete the element at the position i. Might return ErrIndexOutOfBounds.
func Int64Delete(sl *[]int64, i int) error {
	if i < 0 || i >= len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append((*sl)[:i], (*sl)[i+1:]...)
	return nil
}

//Int64Push is equivalent to Int64Insert with index len(*sl)
func Int64Push(sl *[]int64, elem int64) {
	Int64Insert(sl, elem, len(*sl))
}

//Int64Pop is equivalent to getting and removing the last element of the slice. Might return ErrEmptySlice.
func Int64Pop(sl *[]int64) (int64, error) {
	if len(*sl) == 0 {
		var zeroVal int64
		return zeroVal, ErrEmptySlice
	}
	last := len(*sl) - 1
	ret := (*sl)[last]
	Int64Delete(sl, last)
	return ret, nil
}

//Int64Equals compares two int64 slices. Returns true if their elements are equal.
func Int64Equals(a, b []int64) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

//Int64FastShuffle will randomly swap the int64 elements of a slice using math/rand (fast but not cryptographycally secure).
func Int64FastShuffle(sp []int64) {
	rand.Shuffle(len(sp), func(i, j int) {
		sp[i], sp[j] = sp[j], sp[i]
	})
}

//Int64SecureShuffle will randomly swap the int64 elements of a slice using crypto/rand (resource intensive but cryptographycally secure).
func Int64SecureShuffle(sp []int64) error {
	var i int64
	size := int64(len(sp)) - 1
	for i = 0; i < size+1; i++ {
		bigRandI, err := crypto.Int(crypto.Reader, big.NewInt(size))
		if err != nil {
			return err
		}
		randI := bigRandI.Int64()
		sp[size-i], sp[randI] = sp[randI], sp[size-i]
	}
	return nil
}
