// Code generated by yasupGen; DO NOT EDIT.

package yasup

import (
	crypto "crypto/rand"
	"math/big"
	"math/rand"
)

//Int8Insert will append elem at the position i. Might return ErrIndexOutOfBounds.
func Int8Insert(sl *[]int8, elem int8, i int) error {
	if i < 0 || i > len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append(*sl, elem)
	copy((*sl)[i+1:], (*sl)[i:])
	(*sl)[i] = elem
	return nil
}

//Int8Delete delete the element at the position i. Might return ErrIndexOutOfBounds.
func Int8Delete(sl *[]int8, i int) error {
	if i < 0 || i >= len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append((*sl)[:i], (*sl)[i+1:]...)
	return nil
}

//Int8Push is equivalent to Int8Insert with index len(*sl)
func Int8Push(sl *[]int8, elem int8) {
	Int8Insert(sl, elem, len(*sl))
}

//Int8Pop is equivalent to getting and removing the last element of the slice. Might return ErrEmptySlice.
func Int8Pop(sl *[]int8) (int8, error) {
	if len(*sl) == 0 {
		var zeroVal int8
		return zeroVal, ErrEmptySlice
	}
	last := len(*sl) - 1
	ret := (*sl)[last]
	Int8Delete(sl, last)
	return ret, nil
}

//Int8Equals compares two int8 slices. Returns true if their elements are equal.
func Int8Equals(a, b []int8) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

//Int8FastShuffle will randomly swap the int8 elements of a slice using math/rand (fast but not cryptographycally secure).
func Int8FastShuffle(sp []int8) {
	rand.Shuffle(len(sp), func(i, j int) {
		sp[i], sp[j] = sp[j], sp[i]
	})
}

//Int8SecureShuffle will randomly swap the int8 elements of a slice using crypto/rand (resource intensive but cryptographycally secure).
func Int8SecureShuffle(sp []int8) error {
	var i int64
	size := int64(len(sp)) - 1
	for i = 0; i < size+1; i++ {
		bigRandI, err := crypto.Int(crypto.Reader, big.NewInt(size))
		if err != nil {
			return err
		}
		randI := bigRandI.Int64()
		sp[size-i], sp[randI] = sp[randI], sp[size-i]
	}
	return nil
}
