// Code generated by yasupGen; DO NOT EDIT.

package yasup

import (
	crypto "crypto/rand"
	"math/big"
	"math/rand"
)

//IntInsert will append elem at the position i. Might return ErrIndexOutOfBounds.
func IntInsert(sl *[]int, elem int, i int) error {
	if i < 0 || i > len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append(*sl, elem)
	copy((*sl)[i+1:], (*sl)[i:])
	(*sl)[i] = elem
	return nil
}

//IntDelete delete the element at the position i. Might return ErrIndexOutOfBounds.
func IntDelete(sl *[]int, i int) error {
	if i < 0 || i >= len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append((*sl)[:i], (*sl)[i+1:]...)
	return nil
}

//IntPush is equivalent to IntInsert with index len(*sl)
func IntPush(sl *[]int, elem int) {
	IntInsert(sl, elem, len(*sl))
}

//IntPop is equivalent to getting and removing the last element of the slice. Might return ErrEmptySlice.
func IntPop(sl *[]int) (int, error) {
	if len(*sl) == 0 {
		var zeroVal int
		return zeroVal, ErrEmptySlice
	}
	last := len(*sl) - 1
	ret := (*sl)[last]
	IntDelete(sl, last)
	return ret, nil
}

//IntEquals compares two int slices. Returns true if their elements are equal.
func IntEquals(a, b []int) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

//IntFastShuffle will randomly swap the int elements of a slice using math/rand (fast but not cryptographycally secure).
func IntFastShuffle(sp []int) {
	rand.Shuffle(len(sp), func(i, j int) {
		sp[i], sp[j] = sp[j], sp[i]
	})
}

//IntSecureShuffle will randomly swap the int elements of a slice using crypto/rand (resource intensive but cryptographycally secure).
func IntSecureShuffle(sp []int) error {
	var i int64
	size := int64(len(sp)) - 1
	for i = 0; i < size+1; i++ {
		bigRandI, err := crypto.Int(crypto.Reader, big.NewInt(size))
		if err != nil {
			return err
		}
		randI := bigRandI.Int64()
		sp[size-i], sp[randI] = sp[randI], sp[size-i]
	}
	return nil
}
