// Code generated by yasupGen; DO NOT EDIT.

package yasup

import (
	crypto "crypto/rand"
	"math/big"
	"math/rand"
)

//StringInsert will append elem at the position i. Might return ErrIndexOutOfBounds.
func StringInsert(sl *[]string, elem string, i int) error {
	if i < 0 || i > len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append(*sl, elem)
	copy((*sl)[i+1:], (*sl)[i:])
	(*sl)[i] = elem
	return nil
}

//StringDelete delete the element at the position i. Might return ErrIndexOutOfBounds.
func StringDelete(sl *[]string, i int) error {
	if i < 0 || i >= len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append((*sl)[:i], (*sl)[i+1:]...)
	return nil
}

//StringPush is equivalent to StringInsert with index len(*sl)
func StringPush(sl *[]string, elem string) {
	StringInsert(sl, elem, len(*sl))
}

//StringPop is equivalent to getting and removing the last element of the slice. Might return ErrEmptySlice.
func StringPop(sl *[]string) (string, error) {
	if len(*sl) == 0 {
		var zeroVal string
		return zeroVal, ErrEmptySlice
	}
	last := len(*sl) - 1
	ret := (*sl)[last]
	StringDelete(sl, last)
	return ret, nil
}

//StringEquals compares two string slices. Returns true if their elements are equal.
func StringEquals(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

//StringFastShuffle will randomly swap the string elements of a slice using math/rand (fast but not cryptographycally secure).
func StringFastShuffle(sp []string) {
	rand.Shuffle(len(sp), func(i, j int) {
		sp[i], sp[j] = sp[j], sp[i]
	})
}

//StringSecureShuffle will randomly swap the string elements of a slice using crypto/rand (resource intensive but cryptographycally secure).
func StringSecureShuffle(sp []string) error {
	var i int64
	size := int64(len(sp)) - 1
	for i = 0; i < size+1; i++ {
		bigRandI, err := crypto.Int(crypto.Reader, big.NewInt(size))
		if err != nil {
			return err
		}
		randI := bigRandI.Int64()
		sp[size-i], sp[randI] = sp[randI], sp[size-i]
	}
	return nil
}
