// Code generated by yasupGen; DO NOT EDIT.

package yasup

import (
	crypto "crypto/rand"
	"math/big"
	"math/rand"
)

var zeroValueString string

//StringInsert will append elem at the position i. Might return ErrIndexOutOfBounds.
func StringInsert(sl *[]string, elem string, i int) error {
	if i < 0 || i > len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append(*sl, elem)
	copy((*sl)[i+1:], (*sl)[i:])
	(*sl)[i] = elem
	return nil
}

//StringDelete delete the element at the position i. Might return ErrIndexOutOfBounds.
func StringDelete(sl *[]string, i int) error {
	if i < 0 || i >= len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append((*sl)[:i], (*sl)[i+1:]...)
	return nil
}

//StringContains will return true if elem is present in the slice and false otherwise.
func StringContains(sl []string, elem string) bool {
	for i := range sl {
		if sl[i] == elem {
			return true
		}
	}
	return false
}

//StringIndex returns the index of the first instance of elem, or -1 if elem is not present.
func StringIndex(sl []string, elem string) int {
	for i := range sl {
		if sl[i] == elem {
			return i
		}
	}
	return -1
}

//StringLastIndex returns the index of the last instance of elem in the slice, or -1 if elem is not present.
func StringLastIndex(sl []string, elem string) int {
	for i := len(sl) - 1; i >= 0; i-- {
		if sl[i] == elem {
			return i
		}
	}
	return -1
}

//StringCount will return an int representing the amount of times that elem is present in the slice.
func StringCount(sl []string, elem string) int {
	var n int
	for i := range sl {
		if sl[i] == elem {
			n++
		}
	}
	return n
}

//StringPush is equivalent to StringInsert with index len(*sl).
func StringPush(sl *[]string, elem string) {
	StringInsert(sl, elem, len(*sl))
}

//StringFrontPush is equivalent to StringInsert with index 0.
func StringFrontPush(sl *[]string, elem string) {
	StringInsert(sl, elem, 0)
}

//StringPop is equivalent to getting and removing the last element of the slice. Might return ErrEmptySlice.
func StringPop(sl *[]string) (string, error) {
	if len(*sl) == 0 {
		return zeroValueString, ErrEmptySlice
	}
	last := len(*sl) - 1
	ret := (*sl)[last]
	StringDelete(sl, last)
	return ret, nil
}

//StringPop is equivalent to getting and removing the first element of the slice. Might return ErrEmptySlice.
func StringFrontPop(sl *[]string) (string, error) {
	if len(*sl) == 0 {
		return zeroValueString, ErrEmptySlice
	}
	ret := (*sl)[0]
	StringDelete(sl, 0)
	return ret, nil
}

//StringReplace modifies the slice with the first n non-overlapping instances of old replaced by new. If n equals -1, there is no limit on the number of replacements.
func StringReplace(sl []string, old, new string, n int) (replacements int) {
	left := n
	for i := range sl {
		if left == 0 {
			break // no replacements left
		}
		if sl[i] == old {
			sl[i] = new
			left--
		}
	}
	return n - left
}

//StringReplaceAll is equivalent to StringReplace with n = -1.
func StringReplaceAll(sl []string, old, new string) (replacements int) {
	return StringReplace(sl, old, new, -1)
}

//StringEquals compares two string slices. Returns true if their elements are equal.
func StringEquals(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

//StringFastShuffle will randomly swap the string elements of a slice using math/rand (fast but not cryptographycally secure).
func StringFastShuffle(sp []string) {
	rand.Shuffle(len(sp), func(i, j int) {
		sp[i], sp[j] = sp[j], sp[i]
	})
}

//StringSecureShuffle will randomly swap the string elements of a slice using crypto/rand (resource intensive but cryptographically secure).
func StringSecureShuffle(sp []string) error {
	var i int64
	size := int64(len(sp)) - 1
	for i = 0; i < size+1; i++ {
		bigRandI, err := crypto.Int(crypto.Reader, big.NewInt(size))
		if err != nil {
			return err
		}
		randI := bigRandI.Int64()
		sp[size-i], sp[randI] = sp[randI], sp[size-i]
	}
	return nil
}
