// Code generated by yasupGen; DO NOT EDIT.

package yasup_test

import (
	yasup "github.com/j4rv/yasup"
	"testing"
)

func Test_UintInsert(t *testing.T) {
	type testCase struct {
		name     string
		slice    []uint
		insertAt int
	}
	base := []uint{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
	tcs := []testCase{
		{"beginning", []uint{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 0},
		{"middle", []uint{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, len(base) / 2},
		{"end", []uint{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, len(base)},
		{"empty slice", []uint{}, 0},
		{"nil slice", nil, 0},
	}
	for _, tc := range tcs {
		yasup.UintInsert(&tc.slice, 4294967295, tc.insertAt)
		if tc.slice[tc.insertAt] != 4294967295 {
			t.Error(tc)
		}
	}
}

func Test_UintFastShuffle(t *testing.T) {
	shuffles := [][]uint{}
	for i := 0; i < 8; i++ {
		or := []uint{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
		yasup.UintFastShuffle(or)
		shuffles = append(shuffles, or)
	}
	for i := range shuffles {
		for j := range shuffles {
			if i == j {
				continue
			}
			if yasup.UintEquals(shuffles[i], shuffles[j]) {
				// If there is any collision in 8 shuffles, the Shuffle function is probably broken
				t.Fail()
			}
		}
	}
	// check that nil does not panic
	yasup.UintFastShuffle(nil)
}

func Test_UintSecureShuffle(t *testing.T) {
	shuffles := [][]uint{}
	for i := 0; i < 8; i++ {
		or := []uint{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
		yasup.UintSecureShuffle(or)
		shuffles = append(shuffles, or)
	}
	for i := range shuffles {
		for j := range shuffles {
			if i == j {
				continue
			}
			if yasup.UintEquals(shuffles[i], shuffles[j]) {
				// If there is any collision in 8 shuffles, the Shuffle function is probably broken
				t.Fail()
			}
		}
	}
	// check that nil does not panic
	yasup.UintSecureShuffle(nil)
}

func Test_UintEquals(t *testing.T) {
	type TestCase struct {
		name string
		a, b []uint
		exp  bool
	}
	tcs := []TestCase{
		// nil checks
		{"Equals nil", nil, nil, true},
		// golang treats empty and nil slices as the same thing in most cases, we'll do the same
		{"Left nil, right empty", nil, []uint{}, true},
		{"Right nil, left empty", []uint{}, nil, true},
		{"Left nil, right not empty", nil, []uint{4294967295}, false},
		{"Right nil, left not empty", []uint{4294967295}, nil, false},

		{"Equals empty", []uint{}, []uint{}, true},
		{"Equals 1", []uint{4294967295}, []uint{4294967295}, true},
		{"Equals 2", []uint{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, []uint{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, true},
		{"Not equals 1", []uint{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, []uint{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 4294967295}, false},
		{"Not equals 2", []uint{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, []uint{}, false},
		{"Not equals 3", []uint{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, []uint{4294967295, 4294967295}, false},
	}
	for _, tc := range tcs {
		got := yasup.UintEquals(tc.a, tc.b)
		if got != tc.exp {
			t.Error(tc)
		}
	}
}
