// Code generated by yasupGen; DO NOT EDIT.

package yasup

import (
	crypto "crypto/rand"
	"math/big"
	"math/rand"
)

var zeroValueUint32 uint32

//Uint32Insert will append elem at the position i. Might return ErrIndexOutOfBounds.
func Uint32Insert(sl *[]uint32, elem uint32, i int) error {
	if i < 0 || i > len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append(*sl, elem)
	copy((*sl)[i+1:], (*sl)[i:])
	(*sl)[i] = elem
	return nil
}

//Uint32Delete delete the element at the position i. Might return ErrIndexOutOfBounds.
func Uint32Delete(sl *[]uint32, i int) error {
	if i < 0 || i >= len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append((*sl)[:i], (*sl)[i+1:]...)
	return nil
}

//Uint32Contains will return true if elem is present in the slice and false otherwise.
func Uint32Contains(sl []uint32, elem uint32) bool {
	for i := range sl {
		if sl[i] == elem {
			return true
		}
	}
	return false
}

//Uint32Index returns the index of the first instance of elem, or -1 if elem is not present.
func Uint32Index(sl []uint32, elem uint32) int {
	for i := range sl {
		if sl[i] == elem {
			return i
		}
	}
	return -1
}

//Uint32LastIndex returns the index of the last instance of elem in the slice, or -1 if elem is not present.
func Uint32LastIndex(sl []uint32, elem uint32) int {
	for i := len(sl) - 1; i >= 0; i-- {
		if sl[i] == elem {
			return i
		}
	}
	return -1
}

//Uint32Count will return an int representing the amount of times that elem is present in the slice.
func Uint32Count(sl []uint32, elem uint32) int {
	var n int
	for i := range sl {
		if sl[i] == elem {
			n++
		}
	}
	return n
}

//Uint32Push is equivalent to Uint32Insert with index len(*sl).
func Uint32Push(sl *[]uint32, elem uint32) {
	Uint32Insert(sl, elem, len(*sl))
}

//Uint32FrontPush is equivalent to Uint32Insert with index 0.
func Uint32FrontPush(sl *[]uint32, elem uint32) {
	Uint32Insert(sl, elem, 0)
}

//Uint32Pop is equivalent to getting and removing the last element of the slice. Might return ErrEmptySlice.
func Uint32Pop(sl *[]uint32) (uint32, error) {
	if len(*sl) == 0 {
		return zeroValueUint32, ErrEmptySlice
	}
	last := len(*sl) - 1
	ret := (*sl)[last]
	Uint32Delete(sl, last)
	return ret, nil
}

//Uint32Pop is equivalent to getting and removing the first element of the slice. Might return ErrEmptySlice.
func Uint32FrontPop(sl *[]uint32) (uint32, error) {
	if len(*sl) == 0 {
		return zeroValueUint32, ErrEmptySlice
	}
	ret := (*sl)[0]
	Uint32Delete(sl, 0)
	return ret, nil
}

//Uint32Replace modifies the slice with the first n non-overlapping instances of old replaced by new. If n equals -1, there is no limit on the number of replacements.
func Uint32Replace(sl []uint32, old, new uint32, n int) (replacements int) {
	left := n
	for i := range sl {
		if left == 0 {
			break // no replacements left
		}
		if sl[i] == old {
			sl[i] = new
			left--
		}
	}
	return n - left
}

//Uint32ReplaceAll is equivalent to Uint32Replace with n = -1.
func Uint32ReplaceAll(sl []uint32, old, new uint32) (replacements int) {
	return Uint32Replace(sl, old, new, -1)
}

//Uint32Equals compares two uint32 slices. Returns true if their elements are equal.
func Uint32Equals(a, b []uint32) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

//Uint32FastShuffle will randomly swap the uint32 elements of a slice using math/rand (fast but not cryptographycally secure).
func Uint32FastShuffle(sp []uint32) {
	rand.Shuffle(len(sp), func(i, j int) {
		sp[i], sp[j] = sp[j], sp[i]
	})
}

//Uint32SecureShuffle will randomly swap the uint32 elements of a slice using crypto/rand (resource intensive but cryptographically secure).
func Uint32SecureShuffle(sp []uint32) error {
	var i int64
	size := int64(len(sp)) - 1
	for i = 0; i < size+1; i++ {
		bigRandI, err := crypto.Int(crypto.Reader, big.NewInt(size))
		if err != nil {
			return err
		}
		randI := bigRandI.Int64()
		sp[size-i], sp[randI] = sp[randI], sp[size-i]
	}
	return nil
}
