// Code generated by yasupGen; DO NOT EDIT.

package yasup_test

import (
	yasup "github.com/j4rv/yasup"
	"testing"
)

func Test_Uint16Insert(t *testing.T) {
	type testCase struct {
		name     string
		slice    []uint16
		insertAt int
	}
	base := []uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
	tcs := []testCase{
		{"beginning", []uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 0},
		{"middle", []uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, len(base) / 2},
		{"end", []uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, len(base)},
		{"empty slice", []uint16{}, 0},
		{"nil slice", nil, 0},
	}
	for _, tc := range tcs {
		yasup.Uint16Insert(&tc.slice, 65535, tc.insertAt)
		if tc.slice[tc.insertAt] != 65535 {
			t.Error(tc)
		}
	}
}

func Test_Uint16Insert(t *testing.T) {
	type testCase struct {
		name     string
		slice    []uint16
		insertAt int
	}
	base := []uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
	tcs := []testCase{
		{"First", []uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 0},
		{"Middle", []uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, len(base) / 2},
		{"Last", []uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, len(base)},
		{"Empty slice", []uint16{}, 0},
		{"Nil slice", nil, 0},
	}
	for _, tc := range tcs {
		slices.Uint16Insert(65535, &tc.slice, tc.insertAt)
		if tc.slice[tc.insertAt] != 65535 {
			t.Error(tc)
		}
	}
}

func Test_Uint16FastShuffle(t *testing.T) {
	shuffles := [][]uint16{}
	for i := 0; i < 8; i++ {
		or := []uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
		yasup.Uint16FastShuffle(or)
		shuffles = append(shuffles, or)
	}
	for i := range shuffles {
		for j := range shuffles {
			if i >= j {
				continue
			}
			if yasup.Uint16Equals(shuffles[i], shuffles[j]) {
				// If there is any collision in 8 shuffles, the Shuffle function is probably broken
				t.Fail()
			}
		}
	}
	// check that nil does not panic
	yasup.Uint16FastShuffle(nil)
}

func Test_Uint16SecureShuffle(t *testing.T) {
	shuffles := [][]uint16{}
	for i := 0; i < 8; i++ {
		or := []uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
		yasup.Uint16SecureShuffle(or)
		shuffles = append(shuffles, or)
	}
	for i := range shuffles {
		for j := range shuffles {
			if i >= j {
				continue
			}
			if yasup.Uint16Equals(shuffles[i], shuffles[j]) {
				// If there is any collision in 8 shuffles, the Shuffle function is probably broken
				t.Fail()
			}
		}
	}
	// check that nil does not panic
	yasup.Uint16SecureShuffle(nil)
}

func Test_Uint16Equals(t *testing.T) {
	type TestCase struct {
		name string
		a, b []uint16
		exp  bool
	}
	tcs := []TestCase{
		// nil checks
		{"Equals nil", nil, nil, true},
		// golang treats empty and nil slices as the same thing in most cases, we'll do the same
		{"Left nil, right empty", nil, []uint16{}, true},
		{"Right nil, left empty", []uint16{}, nil, true},
		{"Left nil, right not empty", nil, []uint16{65535}, false},
		{"Right nil, left not empty", []uint16{65535}, nil, false},

		{"Equals empty", []uint16{}, []uint16{}, true},
		{"Equals 1", []uint16{65535}, []uint16{65535}, true},
		{"Equals 2", []uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, []uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, true},
		{"Not equals 1", []uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, []uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 65535}, false},
		{"Not equals 2", []uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, []uint16{}, false},
		{"Not equals 3", []uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, []uint16{65535, 65535}, false},
	}
	for _, tc := range tcs {
		got := yasup.Uint16Equals(tc.a, tc.b)
		if got != tc.exp {
			t.Error(tc)
		}
	}
}
