// Code generated by yasupGen; DO NOT EDIT.

package yasup_test

import (
	yasup "github.com/j4rv/yasup"
	"testing"
)

func Test_Uint8Insert(t *testing.T) {
	type testCase struct {
		name     string
		slice    []uint8
		insertAt int
	}
	base := []uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
	tcs := []testCase{
		{"First", []uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, 0},
		{"Middle", []uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, len(base) / 2},
		{"Last", []uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, len(base)},
		{"Empty slice", []uint8{}, 0},
		{"Nil slice", nil, 0},
	}
	for _, tc := range tcs {
		yasup.Uint8Insert(&tc.slice, 255, tc.insertAt)
		if tc.slice[tc.insertAt] != 255 {
			t.Error(tc)
		}
	}
}

func Test_Uint8FastShuffle(t *testing.T) {
	shuffles := [][]uint8{}
	for i := 0; i < 8; i++ {
		or := []uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
		yasup.Uint8FastShuffle(or)
		shuffles = append(shuffles, or)
	}
	for i := range shuffles {
		for j := range shuffles {
			if i >= j {
				continue
			}
			if yasup.Uint8Equals(shuffles[i], shuffles[j]) {
				// If there is any collision in 8 shuffles, the Shuffle function is probably broken
				t.Fail()
			}
		}
	}
	// check that nil does not panic
	yasup.Uint8FastShuffle(nil)
}

func Test_Uint8SecureShuffle(t *testing.T) {
	shuffles := [][]uint8{}
	for i := 0; i < 8; i++ {
		or := []uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
		yasup.Uint8SecureShuffle(or)
		shuffles = append(shuffles, or)
	}
	for i := range shuffles {
		for j := range shuffles {
			if i >= j {
				continue
			}
			if yasup.Uint8Equals(shuffles[i], shuffles[j]) {
				// If there is any collision in 8 shuffles, the Shuffle function is probably broken
				t.Fail()
			}
		}
	}
	// check that nil does not panic
	yasup.Uint8SecureShuffle(nil)
}

func Test_Uint8Equals(t *testing.T) {
	type TestCase struct {
		name string
		a, b []uint8
		exp  bool
	}
	tcs := []TestCase{
		// nil checks
		{"Equals nil", nil, nil, true},
		// golang treats empty and nil slices as the same thing in most cases, we'll do the same
		{"Left nil, right empty", nil, []uint8{}, true},
		{"Right nil, left empty", []uint8{}, nil, true},
		{"Left nil, right not empty", nil, []uint8{255}, false},
		{"Right nil, left not empty", []uint8{255}, nil, false},

		{"Equals empty", []uint8{}, []uint8{}, true},
		{"Equals 1", []uint8{255}, []uint8{255}, true},
		{"Equals 2", []uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, []uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, true},
		{"Not equals 1", []uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, []uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 255}, false},
		{"Not equals 2", []uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, []uint8{}, false},
		{"Not equals 3", []uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, []uint8{255, 255}, false},
	}
	for _, tc := range tcs {
		got := yasup.Uint8Equals(tc.a, tc.b)
		if got != tc.exp {
			t.Error(tc)
		}
	}
}
