// Code generated by yasupGen; DO NOT EDIT.

package yasup

import (
	crypto "crypto/rand"
	"math/big"
	"math/rand"
)

//Uint32Contains will return true if elem is present in the slice and false otherwise.
func Uint32Contains(sl []uint32, elem uint32) bool {
	for i := range sl {
		if sl[i] == elem {
			return true
		}
	}
	return false
}

//Uint32Insert will append elem at the position i. Might return ErrIndexOutOfBounds.
func Uint32Insert(sl *[]uint32, elem uint32, i int) error {
	if i < 0 || i > len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append(*sl, elem)
	copy((*sl)[i+1:], (*sl)[i:])
	(*sl)[i] = elem
	return nil
}

//Uint32Delete delete the element at the position i. Might return ErrIndexOutOfBounds.
func Uint32Delete(sl *[]uint32, i int) error {
	if i < 0 || i >= len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append((*sl)[:i], (*sl)[i+1:]...)
	return nil
}

//Uint32Push is equivalent to Uint32Insert with index len(*sl)
func Uint32Push(sl *[]uint32, elem uint32) {
	Uint32Insert(sl, elem, len(*sl))
}

//Uint32Pop is equivalent to getting and removing the last element of the slice. Might return ErrEmptySlice.
func Uint32Pop(sl *[]uint32) (uint32, error) {
	if len(*sl) == 0 {
		var zeroVal uint32
		return zeroVal, ErrEmptySlice
	}
	last := len(*sl) - 1
	ret := (*sl)[last]
	Uint32Delete(sl, last)
	return ret, nil
}

//Uint32Equals compares two uint32 slices. Returns true if their elements are equal.
func Uint32Equals(a, b []uint32) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

//Uint32FastShuffle will randomly swap the uint32 elements of a slice using math/rand (fast but not cryptographycally secure).
func Uint32FastShuffle(sp []uint32) {
	rand.Shuffle(len(sp), func(i, j int) {
		sp[i], sp[j] = sp[j], sp[i]
	})
}

//Uint32SecureShuffle will randomly swap the uint32 elements of a slice using crypto/rand (resource intensive but cryptographycally secure).
func Uint32SecureShuffle(sp []uint32) error {
	var i int64
	size := int64(len(sp)) - 1
	for i = 0; i < size+1; i++ {
		bigRandI, err := crypto.Int(crypto.Reader, big.NewInt(size))
		if err != nil {
			return err
		}
		randI := bigRandI.Int64()
		sp[size-i], sp[randI] = sp[randI], sp[size-i]
	}
	return nil
}
