// Code generated by yasupGen; DO NOT EDIT.

package yasup

import (
	crypto "crypto/rand"
	"math/big"
	"math/rand"
)

//Uint8Contains will return true if elem is present in the slice and false otherwise.
func Uint8Contains(sl []uint8, elem uint8) bool {
	for i := range sl {
		if sl[i] == elem {
			return true
		}
	}
	return false
}

//Uint8Insert will append elem at the position i. Might return ErrIndexOutOfBounds.
func Uint8Insert(sl *[]uint8, elem uint8, i int) error {
	if i < 0 || i > len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append(*sl, elem)
	copy((*sl)[i+1:], (*sl)[i:])
	(*sl)[i] = elem
	return nil
}

//Uint8Delete delete the element at the position i. Might return ErrIndexOutOfBounds.
func Uint8Delete(sl *[]uint8, i int) error {
	if i < 0 || i >= len(*sl) {
		return ErrIndexOutOfBounds
	}
	*sl = append((*sl)[:i], (*sl)[i+1:]...)
	return nil
}

//Uint8Push is equivalent to Uint8Insert with index len(*sl)
func Uint8Push(sl *[]uint8, elem uint8) {
	Uint8Insert(sl, elem, len(*sl))
}

//Uint8Pop is equivalent to getting and removing the last element of the slice. Might return ErrEmptySlice.
func Uint8Pop(sl *[]uint8) (uint8, error) {
	if len(*sl) == 0 {
		var zeroVal uint8
		return zeroVal, ErrEmptySlice
	}
	last := len(*sl) - 1
	ret := (*sl)[last]
	Uint8Delete(sl, last)
	return ret, nil
}

//Uint8Equals compares two uint8 slices. Returns true if their elements are equal.
func Uint8Equals(a, b []uint8) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

//Uint8FastShuffle will randomly swap the uint8 elements of a slice using math/rand (fast but not cryptographycally secure).
func Uint8FastShuffle(sp []uint8) {
	rand.Shuffle(len(sp), func(i, j int) {
		sp[i], sp[j] = sp[j], sp[i]
	})
}

//Uint8SecureShuffle will randomly swap the uint8 elements of a slice using crypto/rand (resource intensive but cryptographycally secure).
func Uint8SecureShuffle(sp []uint8) error {
	var i int64
	size := int64(len(sp)) - 1
	for i = 0; i < size+1; i++ {
		bigRandI, err := crypto.Int(crypto.Reader, big.NewInt(size))
		if err != nil {
			return err
		}
		randI := bigRandI.Int64()
		sp[size-i], sp[randI] = sp[randI], sp[size-i]
	}
	return nil
}
