package main

import "text/template"

/*
  TODO testing:
   * Insert (out of bounds test)
   * Delete
   * Pop
   * Push
*/

var testTemplate = template.Must(template.New("").Parse(`
// Code generated by yasupGen; DO NOT EDIT.

package {{.FilePackageSimple}}_test

import (
	"testing"
	yasup "{{.FilePackage}}"
	{{ if .TypePackage }}"{{ .TypePackage }}"{{ end }}
)

func Test_{{.TypeCased}}Insert(t *testing.T) {
	type testCase struct {
		name     string
		slice    []{{.Type}}
		insertAt int
	}
	base := []{{.Type}}{ {{.MultipleVals}} }
	tcs := []testCase{
		testCase{"beginning", []{{.Type}}{ {{.MultipleVals}} }, 0},
		testCase{"middle", []{{.Type}}{ {{.MultipleVals}} }, len(base) / 2},
		testCase{"end", []{{.Type}}{ {{.MultipleVals}} }, len(base)},
		testCase{"empty slice", []{{.Type}}{}, 0},
		testCase{"nil slice", nil, 0},
	}
	for _, tc := range tcs {
		yasup.{{.TypeCased}}Insert(&tc.slice, {{.SingleVal}}, tc.insertAt)
		if (tc.slice[tc.insertAt] != {{.SingleVal}}) {
			t.Error(tc)
		}
	}
}

func Test_{{.TypeCased}}FastShuffle(t *testing.T) {
	shuffles := [][]{{.Type}}{}
	for i := 0; i < 8; i++ {
		or := []{{.Type}}{ {{.MultipleVals}} }
		yasup.{{.TypeCased}}FastShuffle(or)
		shuffles = append(shuffles, or)
	}
	for i := range shuffles {
		for j := range shuffles {
			if i == j {
				continue
			}
			if yasup.{{.TypeCased}}Equals(shuffles[i], shuffles[j]) {
				// If there is any collision in 8 shuffles, the Shuffle function is probably broken
				t.Fail()
			}
		}
	}
	// check that nil does not panic
	yasup.{{.TypeCased}}FastShuffle(nil)
}

func Test_{{.TypeCased}}SecureShuffle(t *testing.T) {
	shuffles := [][]{{.Type}}{}
	for i := 0; i < 8; i++ {
		or := []{{.Type}}{ {{.MultipleVals}} }
		yasup.{{.TypeCased}}SecureShuffle(or)
		shuffles = append(shuffles, or)
	}
	for i := range shuffles {
		for j := range shuffles {
			if i == j {
				continue
			}
			if yasup.{{.TypeCased}}Equals(shuffles[i], shuffles[j]) {
				// If there is any collision in 8 shuffles, the Shuffle function is probably broken
				t.Fail()
			}
		}
	}
	// check that nil does not panic
	yasup.{{.TypeCased}}SecureShuffle(nil)
}

func Test_{{.TypeCased}}Equals(t *testing.T) {
	type TestCase struct {
		name string
		a, b []{{.Type}}
		exp  bool
	}
	tcs := []TestCase{
		// nil checks
		TestCase{"Equals nil", nil, nil, true},
		// golang treats empty and nil slices as the same thing in most cases, we'll do the same
		TestCase{"Left nil, right empty", nil, []{{.Type}}{}, true},
		TestCase{"Right nil, left empty", []{{.Type}}{}, nil, true},
		TestCase{"Left nil, right not empty", nil, []{{.Type}}{ {{.SingleVal}} }, false},
		TestCase{"Right nil, left not empty", []{{.Type}}{ {{.SingleVal}} }, nil, false},

		TestCase{"Equals empty", []{{.Type}}{}, []{{.Type}}{}, true},
		TestCase{"Equals 1", []{{.Type}}{ {{.SingleVal}} }, []{{.Type}}{ {{.SingleVal}} }, true},
		TestCase{"Equals 2", []{{.Type}}{ {{.MultipleVals}} }, []{{.Type}}{ {{.MultipleVals}} }, true},
		TestCase{"Not equals 1", []{{.Type}}{ {{.MultipleVals}} }, []{{.Type}}{ {{.MultipleVals}}, {{.SingleVal}} }, false},
		TestCase{"Not equals 2", []{{.Type}}{ {{.MultipleVals}} }, []{{.Type}}{}, false},
		TestCase{"Not equals 3", []{{.Type}}{ {{.MultipleVals}} }, []{{.Type}}{ {{.SingleVal}}, {{.SingleVal}} }, false},
	}
	for _, tc := range tcs {
		got := yasup.{{.TypeCased}}Equals(tc.a, tc.b)
		if got != tc.exp {
			t.Error(tc)
		}
	}
}
`))
